#Joseph O'Rourke
#Questions to orourke@cs.smith.edu

#-----------------------------------------
inpoly:	inpoly.o
	gcc -o inpoly inpoly.o
inpoly.o: inpoly.c
	gcc -c inpoly.c

#-----------------------------------------
