#Joseph O'Rourke
#Questions to orourke@cs.smith.edu
#make sphere:	compiles sphere.c
#make cube:	compiles cube.c
#make spiral:	compiles spiral.c

#-----------------------------------------
sphere:	sphere.o
	gcc -o sphere sphere.o -lm
sphere.o: sphere.c
	gcc -c sphere.c

#-----------------------------------------
cube:	cube.o
	gcc -o cube cube.o -lm
cube.o: cube.c
	gcc -c cube.c
#-----------------------------------------

#-----------------------------------------
spiral:	spiral.o
	gcc -o spiral spiral.o -lm
spiral.o: spiral.c
	gcc -c spiral.c
#-----------------------------------------
